<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Image\weather-forcast-storm-rain-thunder-day_108615.png" />
    <Resource Include="Resources\Fonts\ofont.ru_SonyEricssonLogo.ttf" />
  </ItemGroup>

</Project>
